version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    volumes:
    - .:/app
    links:
    - redis
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:5000"
    # command: python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:5000
    ports:
    - "5000:5000"
    depends_on:
      - db
  redis:
    image: redis
volumes:
  logvolume01: {}